#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Customize to your needs...
export LC_ALL=en_US.UTF-8
export ANDROID_HOME=$HOME/Developer/android-sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools

#export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
export CLASSPATH=.:$JAVA_HOME/lib

export MYSQL="/usr/local/bin/mysql"
export MYSQL_USER="root"
export MYSQL_SOCK="/tmp/mysql.sock"

alias bean='/usr/local/bin/beanstalkd -d -l 127.0.0.1 -p 11300'
alias mou="open /Applicaions/Mou.app"
alias vi="/usr/local/bin/vim"

export HOMEBREW_GITHUB_API_TOKEN=28668c3e24316c5e90e8a2efe48fddb4c386c749
