#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt clobber

# Customize to your needs...
function jump {
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function marks {
    \ls -l "$MARKPATH" | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
}
function unmark {
    rm -i "$MARKPATH/$1"
}

function _completemarks {
  reply=($(ls $MARKPATH))
}

compctl -K _completemarks jump
compctl -K _completemarks unmark

settitle() { printf "\e]0;$@\a" }
dir_in_title() { settitle `basename $PWD` }
chpwd_functions=(dir_in_title)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias vi="vim"
source /Library/GoogleCorpSupport/srcfs/shell_completion/enable_completion.sh

function renew_gcert_ifneeded() {
  HOURS_TILL_EOB=$((20 - $(date +%-H)))h
  gcertstatus -ssh_cert_comment=corp/normal -check_remaining=$HOURS_TILL_EOB || gcert
}
function renew_bagpipe_ifneeded() {
  p4 info > /dev/null 2>&1 || p4 bagpipe-prodaccess
}
function prodaccess() {
  renew_gcert_ifneeded && renew_bagpipe_ifneeded
}
